### PR TITLE
Added roadsandlibraries

### PR DESCRIPTION
**Pull request by jnaneswar**
# Pull Request Template

## Description
Gave solution for Roads and Libraries challenge from hackerrank.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Checklist:

- [ yes] My code follows the style guidelines of this project
- [yes ] I have performed a self-review of my own code
- [ yes] I have commented my code, particularly in hard-to-understand areas
- [ yes] My changes generate no new warnings

### CODE REVIEW

**Comment by GouravRusiya30** [comment]
Thanks @jnaneswar for contributing.
Can you also update the problem and solution links into the README file ?

**Comment by jnaneswar** [comment]
can u add this repo to hacktober fest

**Comment by GouravRusiya30** [comment]
Can you update Readme file ?
Else I have to reject your PR

**Comment by jnaneswar** [comment]
Let me edit the readme file

**Pull request merged**
